import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"

import { Box, Flex, Heading, SimpleGrid, Text } from "@chakra-ui/react"

import Layout from "../components/layout/layout"
import LinkBox from "../components/lib/linkBox"

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>anfear.co | nextjs12 sandbox</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="Next.js 12 fun!" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <Flex direction="column" align="center" justify="center" py={5} mb={5}>
          <Heading>
            Welcome to a <a href="https://nextjs.org">Next.js sandbox!</a>
          </Heading>
          <Text as="b">{"Let's have some fun!"}</Text>
        </Flex>

        <SimpleGrid columns={2} spacing={5}>
          <LinkBox href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </LinkBox>

          <LinkBox href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </LinkBox>

          <LinkBox href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </LinkBox>

          <LinkBox href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </LinkBox>
        </SimpleGrid>
      </Box>
    </Layout>
  )
}

export default Home
